trigger:
- main  # or your default branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  PYTHON_VERSION: '3.13'  # Adjust if needed

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(PYTHON_VERSION)'
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    pytest --alluredir=allure-results
  displayName: 'Run tests with Allure'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'   # pytest can produce junit xml with --junitxml option if you want to add it
    testResultsFiles: '**/TEST-*.xml'
    failTaskOnFailedTests: true
  condition: succeededOrFailed()

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'allure-results'
    ArtifactName: 'allure-results'
    publishLocation: 'Container'
