trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  pythonVersion: '3.10'

steps:
# Set up Python
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(pythonVersion)'
    addToPath: true

# Install dependencies
- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

# Run Pytest and generate Allure raw results
- script: |
    pytest --alluredir=allure-results
  displayName: 'Run tests with Allure'

# Install Allure CLI (via Snap for Ubuntu agent)
- script: |
    sudo apt update
    sudo apt install -y default-jre
    sudo snap install allure --classic
  displayName: 'Install Allure CLI'

# Generate Allure report from results
- script: |
    allure generate allure-results --clean -o allure-report
  displayName: 'Generate Allure HTML Report'

# Publish Allure report as artifact so it can be downloaded/viewed
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'allure-report'
    artifactName: 'AllureReport'
    publishLocation: 'Container'
  displayName: 'Publish Allure Report Artifact'
